### ISSUE TITLE
23/3/2017 Feedback

### ISSUE THREAD

**Issue by bernardyip** [CS2103JAN2017-T16-B2/main#143]
- Redo UI Component by today
- Put recurring task in Model component
- Write who wrote what in the documentation stuff (All done together)
- Good idea to show breakdown of each component in the same feature
- partial search "y f" does not make sense, think of something to respond to that
- Today should show the deadlines with tasks (Mention this in docuentation, today counter is for task to do today so that future deadlines can be met)
- Shorten the length of lifelines in sequence diagrams
- Consider mark and unmark instead of mark completed/incomplete
- what more useful information can you provide in the left panel? (Show bookings)
- Task title omitted location when date (by deadline) and location both provided
- Consider changing to Draw.io because it allows pointing to initialization of lifelines and ending lifelines (in line with CS2103 conventions)

**Comment by yeshasimaria** [comment]
Merged with my comments
