### ISSUE TITLE
V0.3 feedback

### ISSUE THREAD

**Issue by brandonyeoxg** [CS2103JAN2017-T16-B2/main#154]
**Regarding User Guide:**
Perhaps add more partial screenshots that captures the usage of command(s)?

The 'Command summary' section will be used heavily by our testers. Good job giving examples for each command.

**Regarding Developer Guide:**
Good job updating the developer guide =).

![changeable](https://cloud.githubusercontent.com/assets/16134861/24319311/f30f173a-1152-11e7-9669-4f63598faf98.PNG)
Perhaps you guys can explain what the interface Changeable is for? 

![savedata](https://cloud.githubusercontent.com/assets/16134861/24319349/64bc7b38-1154-11e7-849e-26836dc96592.PNG)
Shouldn't there be a return arrow?

Good job having a comprehensive list for the product survey =). Perhaps it would be clearer if it was to be in a table?

It may be more practical to give a few examples of interesting test cases and explain the thinking behind how you arrived at those test cases, rather than try to give a comprehensive list of all test cases.

Perhaps explain how your design support undo/redo. There are multiple ways this can be done, so it will be useful to explain how you do it and why you chose to do it that way.

_Glossary:_
Perhaps glossary could be updated with terms for floating task, attachments and such?

**Overall:**
Try to do a peer review on each other's PRs.
Please close this issue after reading it.

**Comment by zyjames** [comment]
@brandonyeoxg for the changeable interface, I realised that I created that interface for my previous implementation of the Undo command. I have updated the interface and updated the development guide. The updates will be reflected in the next milestone. Thanks for looking through our development guide and giving some feedback and suggestions for improvement!
