### ISSUE TITLE
Feedback for 06/04/17

### ISSUE THREAD

**Issue by zyjames** [CS2103JAN2017-T16-B2/main#197]
Recurring task
Change date for recurring task, the next date created should not change after editing the date of the task.
Should let user change that instance or all instance.
Should perhaps consider implementing abstraction occurrence pattern design.

Test bugs
Try find bugs and fix them when ever possible.

Test scripts
Come out with test scripts.

**Comment by bernardyip** [comment]
Acknowledged

**Comment by yeshasimaria** [comment]
Addressed
